import { useEffect, useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetCurrentDailyChallengeQueryKey, getGetStaffDailyChallengeQueryKey, getListChallengeSubmissionsQueryKey, useGetMonthlyEngagementMetrics, useGetStaffDailyChallenge, useListChallengeSubmissions, useSaveDailyChallenge, useUpdateChallengeSubmission, type DailyChallengeInput } from '@workspace/api-client-react';
import { errorMessage } from '@/hooks/use-ward';

const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const empty=():DailyChallengeInput=>({title:'',instructions:'',category:'Creative',startDate:localDate(),endDate:localDate(),allowSubmissions:false,published:false});
export function StaffChallenge(){
  const qc=useQueryClient(),current=useGetStaffDailyChallenge(),submissions=useListChallengeSubmissions(),metrics=useGetMonthlyEngagementMetrics();
  const save=useSaveDailyChallenge(),review=useUpdateChallengeSubmission();
  const [form,setForm]=useState<DailyChallengeInput>(empty),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState<number|null>(null);
  useEffect(()=>{if(current.data&&current.data.id!==loaded){setForm({title:current.data.title,instructions:current.data.instructions,category:current.data.category,startDate:current.data.startDate,endDate:current.data.endDate,allowSubmissions:current.data.allowSubmissions,published:current.data.published});setLoaded(current.data.id)}},[current.data,loaded]);
  async function submit(e:FormEvent){e.preventDefault();setNotice('');try{await save.mutateAsync({data:form});setNotice('Challenge saved.');await Promise.all([qc.invalidateQueries({queryKey:getGetStaffDailyChallengeQueryKey()}),qc.invalidateQueries({queryKey:getGetCurrentDailyChallengeQueryKey()})])}catch(err){setNotice(errorMessage(err))}}
  async function changeStatus(id:number,status:'Pending'|'Published'|'Hidden'){setNotice('');try{await review.mutateAsync({id,data:{status}});await Promise.all([qc.invalidateQueries({queryKey:getListChallengeSubmissionsQueryKey()}),qc.invalidateQueries({queryKey:getGetCurrentDailyChallengeQueryKey()})])}catch(err){setNotice(errorMessage(err))}}
  return <section className="mb-10" aria-label="Daily challenge and engagement"><div className="mb-4"><p className="eyebrow">Community activity</p><h2 className="display text-3xl">Today’s challenge</h2></div>
    <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-4"><form onSubmit={submit} className="surface p-5 md:p-7 grid sm:grid-cols-2 gap-4"><div className="sm:col-span-2"><label htmlFor="challenge-title" className="label">Challenge title</label><input id="challenge-title" className="field" required maxLength={180} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></div><div className="sm:col-span-2"><label htmlFor="challenge-instructions" className="label">Instructions</label><textarea id="challenge-instructions" className="field" required maxLength={3000} value={form.instructions} onChange={e=>setForm(v=>({...v,instructions:e.target.value}))}/></div><div className="sm:col-span-2"><label htmlFor="challenge-category" className="label">Category</label><input id="challenge-category" className="field" required maxLength={80} value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}/></div><div><label htmlFor="challenge-start" className="label">Start date</label><input id="challenge-start" type="date" className="field" required value={form.startDate} onChange={e=>setForm(v=>({...v,startDate:e.target.value}))}/></div><div><label htmlFor="challenge-end" className="label">End date</label><input id="challenge-end" type="date" className="field" min={form.startDate} required value={form.endDate} onChange={e=>setForm(v=>({...v,endDate:e.target.value}))}/></div><div className="sm:col-span-2 flex flex-wrap gap-5"><label className="flex gap-2 items-center"><input type="checkbox" className="w-5 h-5 accent-[#315a4d]" checked={form.allowSubmissions} onChange={e=>setForm(v=>({...v,allowSubmissions:e.target.checked}))}/> Allow anonymous text entries</label><label className="flex gap-2 items-center"><input type="checkbox" className="w-5 h-5 accent-[#315a4d]" checked={form.published} onChange={e=>setForm(v=>({...v,published:e.target.checked}))}/> Publish</label></div><div className="sm:col-span-2"><button className="btn btn-primary" disabled={save.isPending}>{save.isPending?'Saving…':'Save challenge'}</button></div></form>
    <div className="surface p-5 md:p-7"><p className="eyebrow mb-2">This month</p><h3 className="display text-2xl mb-5">Community at a glance</h3>{metrics.isLoading?<div className="h-36 bg-[#e8eee7] animate-pulse rounded-xl"/>:metrics.isError?<button className="btn btn-outline" onClick={()=>metrics.refetch()}>Retry metrics</button>:metrics.data?<div className="grid grid-cols-2 gap-4">{([['Suggestions received',metrics.data.suggestionsReceived],['Suggestions implemented',metrics.data.suggestionsImplemented],['Activities created',metrics.data.activitiesCreated],['Activity interest clicks',metrics.data.activityInterestClicks],['Requests received',metrics.data.requestsReceived],['Challenge entries',metrics.data.challengeEntries]] as const).map(([label,value])=><div key={label} className="border-t border-[#dfe5da] pt-3"><strong className="display text-3xl">{value}</strong><p className="text-sm text-[#677a6d]">{label}</p></div>)}</div>:null}</div></div>
    {notice&&<p className="inset p-4 mt-3" role="status">{notice}</p>}
    <div className="mt-6"><h3 className="display text-2xl mb-4">Challenge entries</h3>{submissions.isLoading?<div className="surface h-24 animate-pulse"/>:submissions.isError?<button className="btn btn-outline" onClick={()=>submissions.refetch()}>Retry entries</button>:!submissions.data?.length?<p className="text-[#677a6d]">No entries to review yet.</p>:<div className="grid md:grid-cols-2 gap-3">{submissions.data.map(x=><article className="surface p-5" key={x.id}><span className="pill">{x.status}</span><p className="my-4 whitespace-pre-wrap">{x.text}</p><div className="flex flex-wrap gap-2">{(['Published','Hidden','Pending'] as const).filter(s=>s!==x.status).map(status=><button key={status} className="btn btn-outline !min-h-[40px]" disabled={review.isPending} onClick={()=>changeStatus(x.id,status)}>{status==='Published'?'Publish':status==='Hidden'?'Hide':'Return to review'}</button>)}</div></article>)}</div>}</div>
  </section>;
}