import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, BookOpen, ClipboardList, Heart, Lightbulb, MessageSquareText, Sparkles, Trash2 } from 'lucide-react';
import { useGetWardSummary, useListWardItems } from '@workspace/api-client-react';
import { errorMessage, useWardActions } from '@/hooks/use-ward';
import { ItemCard, LinkCard, PageHeading, SectionTitle, State } from '@/components/ward-ui';

export function HomePage() {
  const summary = useGetWardSummary();
  const schedule = useListWardItems('schedule');
  const activities = useListWardItems('activities');
  const announcements = useListWardItems('announcements');
  const today = new Date();
  const todayKey = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
  const todayItems = schedule.data?.filter(item => !item.date || item.date === todayKey) || [];
  const next = activities.data?.filter(item => !item.date || item.date >= todayKey).filter(item => !item.date || item.date !== todayKey || !item.time || item.time >= today.toTimeString().slice(0,5)).sort((a,b)=>(a.date||todayKey).localeCompare(b.date||todayKey)||(a.time||'').localeCompare(b.time||''))[0];
  return <>
    <div className="rounded-[26px] bg-[#dfe7dd] px-6 py-9 md:px-10 md:py-11 mb-10 relative overflow-hidden">
      <div className="absolute -right-24 -top-32 w-80 h-80 rounded-full border-[44px] border-[#ceddd2] opacity-70 pointer-events-none" />
      <p className="eyebrow mb-4 relative">{today.toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' })}</p>
      <h1 className="display text-[clamp(3rem,6vw,5.8rem)] max-w-[650px] relative">A little more room<br />for today.</h1>
      <p className="mt-5 max-w-[500px] text-[#536b5b] text-lg relative">What’s happening, what’s available, and where to find what you need.</p>
      <div className="mt-7 flex flex-wrap gap-3 relative"><Link href="/activities" className="btn btn-primary" data-testid="link-home-activities">Explore activities <ArrowRight size={17}/></Link><Link href="/guide" className="btn btn-outline bg-[#edf1e9]" data-testid="link-home-guide">Open ward guide</Link></div>
    </div>
    <section className="mb-9 grid md:grid-cols-[1.2fr_.8fr] gap-4">
      <div className="rounded-[22px] bg-[#365b50] text-[#f9f6ed] p-6 md:p-8"><p className="eyebrow !text-[#c7d8c9] mb-4">Next activity</p>{activities.isLoading?<div className="h-28 rounded-xl animate-pulse bg-[#527469]" />:activities.isError?<div><p>Couldn't load the next activity.</p><button className="btn btn-light mt-4" onClick={()=>activities.refetch()} data-testid="button-retry-next">Try again</button></div>:next?<div><h2 className="display text-3xl mb-3">{next.title}</h2><p className="text-[#d6e3d7]">{[next.date&&new Date(`${next.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}),next.time,next.location].filter(Boolean).join(' · ')}</p><Link href="/activities" className="btn btn-light mt-6" data-testid="link-view-next-activity">View activities <ArrowRight size={16}/></Link></div>:<><h2 className="display text-2xl">Nothing planned just yet.</h2><Link href="/activities" className="btn btn-light mt-5" data-testid="link-view-next-activity">Explore activities <ArrowRight size={16}/></Link></>}</div>
      <div className="surface p-6 md:p-8"><p className="eyebrow mb-3">Quick actions</p><h2 className="display text-2xl mb-5">What would help today?</h2><div className="flex flex-col gap-2"><Link href="/requests" className="btn btn-soft justify-between" data-testid="link-quick-request">Make a practical request <ArrowRight size={16}/></Link><Link href="/activities?compose=1" className="btn btn-soft justify-between" data-testid="link-quick-activity-idea">Suggest an activity <ArrowRight size={16}/></Link><Link href="/requests?type=suggestion" className="btn btn-soft justify-between" data-testid="link-quick-suggest">Share a suggestion <ArrowRight size={16}/></Link><Link href="/my-stay" className="btn btn-outline justify-between" data-testid="link-quick-stay">Open My Stay <ArrowRight size={16}/></Link></div></div>
    </section>
    <div className="grid sm:grid-cols-3 gap-3 mb-12"><div className="surface p-5"><p className="eyebrow">Today</p><strong className="display text-3xl block mt-2" data-testid="value-today-activities">{summary.data?.todayActivities ?? '—'}</strong><p className="text-sm text-[#69786d]">activities on the calendar</p></div><div className="surface p-5"><p className="eyebrow">Coming up</p><strong className="display text-3xl block mt-2" data-testid="value-upcoming-activities">{summary.data?.upcomingActivities ?? '—'}</strong><p className="text-sm text-[#69786d]">activities ahead</p></div><div className="surface p-5"><p className="eyebrow">Noticeboard</p><strong className="display text-3xl block mt-2" data-testid="value-announcements">{summary.data?.announcements ?? '—'}</strong><p className="text-sm text-[#69786d]">announcements</p></div></div>
    {summary.isError && <p className="mb-6 text-[#9d5547]">Couldn't load today's overview. <button onClick={() => summary.refetch()} className="underline" data-testid="button-retry-summary">Try again</button></p>}
    <section className="mb-12"><SectionTitle title="Today’s rhythm" aside={<Link href="/activities" className="text-sm font-bold text-[#456b5c] flex items-center gap-1" data-testid="link-all-activities">All activities <ArrowRight size={15}/></Link>} /><State loading={schedule.isLoading} error={schedule.isError} empty={!todayItems.length} retry={() => schedule.refetch()}><div className="space-y-3">{todayItems.map(item => <ItemCard key={item.id} item={item} compact />)}</div></State></section>
    <section className="mb-12"><SectionTitle title="From the noticeboard" /><State loading={announcements.isLoading} error={announcements.isError} empty={!announcements.data?.length} retry={() => announcements.refetch()}><div className="grid md:grid-cols-2 gap-4">{announcements.data?.slice(0,4).map(item => <ItemCard key={item.id} item={item} />)}</div></State></section>
    <section><SectionTitle title="Find your way" /><div className="grid md:grid-cols-3 gap-4"><LinkCard to="/things-to-do" label="Things to do" text="Small ways to spend some time." icon={Sparkles}/><LinkCard to="/requests" label="Requests & ideas" text="Share a practical request or a thought." icon={MessageSquareText} tone="peach"/><LinkCard to="/my-stay" label="My stay" text="A private little place for your own notes." icon={ClipboardList}/></div></section>
  </>;
}

export function ActivitiesPage() {
  const activities = useListWardItems('activities');
  const suggestions = useListWardItems('activity-suggestions');
  const [showIdea, setShowIdea] = useState(() => new URLSearchParams(window.location.search).has('compose'));
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [preferredTime, setPreferredTime] = useState('');
  const [category, setCategory] = useState('');
  const [notice, setNotice] = useState('');
  const actions = useWardActions();
  const upcoming = [...(activities.data || [])].sort((a,b) => (a.date || '').localeCompare(b.date || '') || (a.time || '').localeCompare(b.time || ''));
  const popular = [...(activities.data || [])].sort((a,b) => b.interestCount - a.interestCount).slice(0,2);
  return <>
    <PageHeading eyebrow="Make space for something" title="Activities, at your own pace." description="See what’s coming up, find a favourite, or suggest something you’d like to do." action={<button className="btn btn-primary" onClick={() => setShowIdea(v => !v)} data-testid="button-suggest-activity"><Lightbulb size={17}/> Suggest an activity</button>} />
    {showIdea && <form className="surface p-6 md:p-8 mb-9 space-y-4" onSubmit={async e => { e.preventDefault(); try { await actions.create.mutateAsync({kind:'activity-suggestions', data:{title,description,category,preferredTime}}); setTitle(''); setDescription(''); setCategory(''); setPreferredTime(''); setShowIdea(false); setNotice('Thank you. Your idea has been shared.'); } catch(err) { setNotice(errorMessage(err)); } }}><h2 className="display text-2xl">What would you like to try?</h2><p className="text-sm text-[#69786d]">No name needed. This is a non-urgent suggestion.</p><div><label className="label" htmlFor="activity-title">Activity idea</label><input id="activity-title" className="field" required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)} placeholder="For example, a music afternoon" data-testid="input-activity-title"/></div><div><label className="label" htmlFor="activity-description">A little more detail (optional)</label><textarea id="activity-description" className="field" maxLength={3000} value={description} onChange={e=>setDescription(e.target.value)} data-testid="input-activity-description"/></div><div className="grid sm:grid-cols-2 gap-4"><div><label className="label" htmlFor="activity-category">Category (optional)</label><select id="activity-category" className="field" value={category} onChange={e=>setCategory(e.target.value)} data-testid="select-activity-category"><option value="">Choose a category</option>{['Creative','Games','Movement','Music','Social','Quiet time','Other'].map(c=><option key={c}>{c}</option>)}</select></div><div><label className="label" htmlFor="preferred-time">Preferred time (optional)</label><select id="preferred-time" className="field" value={preferredTime} onChange={e=>setPreferredTime(e.target.value)} data-testid="select-preferred-time"><option value="">Choose a time</option>{['Morning','Afternoon','Evening','No preference'].map(t=><option key={t}>{t}</option>)}</select></div></div><button disabled={actions.create.isPending} className="btn btn-primary" data-testid="button-send-activity">{actions.create.isPending ? 'Sharing…' : 'Share idea'}</button></form>}
    {notice && <p role="status" className="inset p-4 mb-8" data-testid="status-activity">{notice}</p>}
    <section className="mb-12"><SectionTitle title="Coming up" /><State loading={activities.isLoading} error={activities.isError} empty={!upcoming.length} retry={()=>activities.refetch()}><div className="grid md:grid-cols-2 gap-4">{upcoming.map(item=><ItemCard key={item.id} item={item} kind="activities"/>)}</div></State></section>
    <section className="mb-12"><SectionTitle title="People are interested in" /><State loading={activities.isLoading} error={activities.isError} empty={!popular.length} retry={()=>activities.refetch()}><div className="grid md:grid-cols-2 gap-4">{popular.map(item=><ItemCard key={item.id} item={item} kind="activities"/>)}</div></State></section>
    <section><SectionTitle title="Ideas from the ward" /><State loading={suggestions.isLoading} error={suggestions.isError} empty={!suggestions.data?.length} retry={()=>suggestions.refetch()}><div className="grid md:grid-cols-2 gap-4">{suggestions.data?.map(item=><ItemCard key={item.id} item={item} kind="activity-suggestions"/>)}</div></State></section>
  </>;
}

export function ThingsPage() {
  const things = useListWardItems('things-to-do');
  const learning = useListWardItems('learning');
  const [category, setCategory] = useState('All');
  const [duration,setDuration] = useState('All');
  const [learnCategory,setLearnCategory] = useState('All');
  const [learnDuration,setLearnDuration] = useState('All');
  const categories = ['All', ...new Set((things.data || []).map(x=>x.category).filter((x): x is string=>!!x))];
  const durations = ['All',...new Set((things.data||[]).map(x=>x.duration).filter((x): x is string=>!!x))];
  const learningCategories = ['All',...new Set((learning.data||[]).map(x=>x.category).filter((x): x is string=>!!x))];
  const learningDurations = ['All',...new Set((learning.data||[]).map(x=>x.duration).filter((x): x is string=>!!x))];
  const filtered = (things.data || []).filter(x => (category === 'All' || x.category === category) && (duration === 'All'||x.duration===duration));
  const filteredLearning = (learning.data||[]).filter(x=>(learnCategory==='All'||x.category===learnCategory)&&(learnDuration==='All'||x.duration===learnDuration));
  return <><PageHeading eyebrow="A moment for yourself" title="Things to do." description="A collection of small activities and something new to learn. Pick what suits this moment." />
    <section className="mb-14"><SectionTitle title="Browse a little" /><div className="grid sm:grid-cols-2 gap-3 mb-5"><div><label htmlFor="things-category" className="label">Category</label><select id="things-category" className="field" value={category} onChange={e=>setCategory(e.target.value)} data-testid="select-things-category">{categories.map(c=><option key={c}>{c}</option>)}</select></div><div><label htmlFor="things-duration" className="label">Duration</label><select id="things-duration" className="field" value={duration} onChange={e=>setDuration(e.target.value)} data-testid="select-things-duration">{durations.map(d=><option key={d}>{d}</option>)}</select></div></div><State loading={things.isLoading} error={things.isError} empty={!filtered.length} retry={()=>things.refetch()}><div className="grid md:grid-cols-2 gap-4">{filtered.map(item=><ItemCard key={item.id} item={item} kind="things-to-do"/>)}</div></State></section>
    <section className="bg-[#e8e9df] rounded-[24px] p-5 sm:p-8"><p className="eyebrow mb-2">A little curiosity</p><SectionTitle title="Learn something" /><div className="grid sm:grid-cols-2 gap-3 mb-5"><div><label htmlFor="learn-category" className="label">Category</label><select id="learn-category" className="field" value={learnCategory} onChange={e=>setLearnCategory(e.target.value)} data-testid="select-learning-category">{learningCategories.map(c=><option key={c}>{c}</option>)}</select></div><div><label htmlFor="learn-duration" className="label">Duration</label><select id="learn-duration" className="field" value={learnDuration} onChange={e=>setLearnDuration(e.target.value)} data-testid="select-learning-duration">{learningDurations.map(d=><option key={d}>{d}</option>)}</select></div></div><State loading={learning.isLoading} error={learning.isError} empty={!filteredLearning.length} retry={()=>learning.refetch()}><div className="space-y-4">{filteredLearning.map(item=><article className="surface p-6 md:p-8" key={item.id} data-testid={`lesson-${item.id}`}><div className="flex gap-2 flex-wrap mb-4">{item.category&&<span className="pill">{item.category}</span>}{item.duration&&<span className="pill">{item.duration}</span>}{item.difficulty&&<span className="pill">{item.difficulty}</span>}</div><h3 className="display text-2xl md:text-3xl">{item.title}</h3>{item.description&&<p className="mt-3 text-[#607368] text-lg leading-relaxed">{item.description}</p>}{item.content&&<div className="whitespace-pre-wrap leading-[1.9] text-[#40584b] mt-6 border-t border-[#e6e2d7] pt-5 max-w-[72ch]">{item.content}</div>}</article>)}</div></State></section>
  </>;
}

export function GuidePage() {
  const guide = useListWardItems('ward-guide');
  const [search, setSearch] = useState('');
  const filtered = (guide.data || []).filter(x => `${x.title} ${x.description||''} ${x.content||''} ${x.category||''}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeading eyebrow="Helpful, in one place" title="The ward guide." description="Answers to everyday questions. If something isn’t here, you can always ask a member of staff directly." />
    <div className="max-w-[600px] mb-8"><label className="label" htmlFor="guide-search">Search the guide</label><input id="guide-search" type="search" className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try meals, visitors, or laundry" data-testid="input-guide-search" /></div>
    <State loading={guide.isLoading} error={guide.isError} empty={!filtered.length} retry={()=>guide.refetch()}><div className="space-y-3 max-w-[820px]">{filtered.map(item=><details key={item.id} className="surface group" data-testid={`faq-${item.id}`}><summary className="list-none cursor-pointer p-5 md:p-6 flex justify-between items-center gap-4 font-semibold text-lg [&::-webkit-details-marker]:hidden"><span>{item.title}</span><span className="text-[#749180] text-2xl font-normal group-open:rotate-45 transition-transform">+</span></summary><div className="px-5 md:px-6 pb-6 text-[#627369] whitespace-pre-line border-t border-[#e7e4d9] pt-4">{item.description}{item.content && <p className="mt-3">{item.content}</p>}</div></details>)}</div></State>
  </>;
}

export function RequestsPage() {
  const [tab, setTab] = useState<'requests'|'suggestions'>(()=>new URLSearchParams(window.location.search).get('type')==='suggestion'?'suggestions':'requests');
  const [title,setTitle] = useState('');
  const [description,setDescription] = useState('');
  const [category,setCategory] = useState('');
  const [location,setLocation] = useState('');
  const [notice,setNotice] = useState('');
  const actions = useWardActions();
  const suggestions = useListWardItems('suggestions');
  return <><PageHeading eyebrow="A place to speak up" title="Requests & ideas." description="For everyday, non-urgent things. You don’t need to leave a name." />
    <div className="rounded-[18px] bg-[#f3e7da] p-5 mb-8 max-w-[840px] border border-[#e9d7c3]"><strong className="text-[#6e5949]">Not for urgent help.</strong><p className="text-[#765f50] mt-1 text-sm">This form is not monitored for emergencies. If you need help now, speak to a member of staff in person.</p></div>
    <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-9">
      <div className="surface p-6 md:p-8 self-start"><div className="flex flex-wrap gap-2 mb-7"><button className={`btn ${tab==='requests'?'btn-primary':'btn-soft'}`} onClick={()=>{setTab('requests');setCategory('');setNotice('')}} data-testid="button-tab-request">Practical request</button><button className={`btn ${tab==='suggestions'?'btn-primary':'btn-soft'}`} onClick={()=>{setTab('suggestions');setCategory('');setNotice('')}} data-testid="button-tab-suggestion">General suggestion</button></div><h2 className="display text-3xl">{tab==='requests'?'Ask for something practical':'Share an idea for the ward'}</h2><p className="text-[#69786d] mt-2 mb-6">{tab==='requests'?'For everyday items or practical needs. Please talk to staff directly for anything urgent.':'An idea about the space, routines, or everyday experience.'}</p>
        <form onSubmit={async e=>{e.preventDefault();try {await actions.create.mutateAsync({kind:tab,data:{title,description,category,location:tab==='requests'?location:undefined}});setTitle('');setDescription('');setCategory('');setLocation('');setNotice(tab==='requests'?'Request submitted. If this is urgent or relates to your health or safety, please speak directly to a member of staff.':'Thank you. Your suggestion has been shared.');}catch(err){setNotice(errorMessage(err))}}} className="space-y-5">
          <div><label className="label" htmlFor="request-category">Category {tab==='requests'?'':'(optional)'}</label><select id="request-category" className="field" required={tab==='requests'} value={category} onChange={e=>setCategory(e.target.value)} data-testid="select-request-category"><option value="">Choose a category</option>{(tab==='requests'?['Toiletries','Bedding','Clothing','Laundry','Books / Games','Room issue','Food / Drink question','Speak to someone','Other practical request']:['Activities','Ward environment','Entertainment','Food suggestions','Facilities','General improvements']).map(c=><option key={c}>{c}</option>)}</select></div>
          <div><label className="label" htmlFor="request-title">{tab==='requests'?'What do you need?':'What’s your idea?'}</label><input id="request-title" required maxLength={180} className="field" value={title} onChange={e=>setTitle(e.target.value)} placeholder={tab==='requests'?'A short description of your request':'A short title for your idea'} data-testid="input-request-title"/></div>
          <div><label className="label" htmlFor="request-detail">More detail (optional)</label><textarea id="request-detail" maxLength={3000} className="field" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Anything else you’d like to add" data-testid="input-request-detail"/></div>
          {tab==='requests'&&<div><label className="label" htmlFor="request-location">Location or room reference (optional)</label><input id="request-location" className="field" maxLength={100} value={location} onChange={e=>setLocation(e.target.value)} placeholder="Only if it helps with this practical request" data-testid="input-request-location"/></div>}
          <button disabled={actions.create.isPending} className="btn btn-primary" data-testid="button-submit-request">{actions.create.isPending?'Sending…':'Send without a name'} <ArrowRight size={17}/></button>
        </form>{notice && <p role="status" className="inset p-4 mt-5 text-sm" data-testid="status-request">{notice}</p>}</div>
      <div><SectionTitle title="You said / We did" /><p className="text-[#69786d] mb-5">Ideas and responses shared with the ward.</p><State loading={suggestions.isLoading} error={suggestions.isError} empty={!suggestions.data?.filter(x=>x.response&&x.published!==false).length} retry={()=>suggestions.refetch()}><div className="space-y-3">{suggestions.data?.filter(x=>x.response&&x.published!==false).map(item=><ItemCard key={item.id} item={item} compact/>)}</div></State></div>
    </div>
  </>;
}

type StayTask = { id: string; text: string; done: boolean };
type StayList = 'ask' | 'sort' | 'today';
type StayData = { tasks: Record<StayList, StayTask[]>; notes: string; checkin: string };
const emptyStay = (): StayData => ({tasks:{ask:[],sort:[],today:[]},notes:'',checkin:''});
const lists: {key:StayList;title:string;placeholder:string}[] = [
  {key:'ask',title:'Things I want to ask',placeholder:'Something I’d like to ask about'},
  {key:'sort',title:'Things I need to sort',placeholder:'Something to remember'},
  {key:'today',title:'Things I want to do today',placeholder:'A small plan for today'},
];
const storageKey = 'wardspace-my-stay';
function loadStay(): StayData { try { const raw = localStorage.getItem(storageKey); if (raw) { const parsed = JSON.parse(raw); const tasks=emptyStay().tasks; for(const {key} of lists) tasks[key]=Array.isArray(parsed.tasks?.[key])?parsed.tasks[key].filter((t:StayTask)=>typeof t?.id==='string'&&typeof t?.text==='string'&&typeof t?.done==='boolean'):[];return {tasks,notes:typeof parsed.notes==='string'?parsed.notes:'',checkin:['Good','Okay','Difficult','Prefer not to say'].includes(parsed.checkin)?parsed.checkin:''}; } } catch { /* unavailable storage starts fresh */ } return emptyStay(); }
export function MyStayPage() {
  const [data,setData] = useState<StayData>(loadStay);
  const [drafts,setDrafts] = useState<Record<StayList,string>>({ask:'',sort:'',today:''});
  const [saved,setSaved] = useState(true);
  function update(next: StayData) { setData(next); try { localStorage.setItem(storageKey,JSON.stringify(next)); setSaved(true); } catch { setSaved(false); } }
  function changeTask(key:StayList,tasks:StayTask[]) { update({...data,tasks:{...data.tasks,[key]:tasks}}); }
  function addTask(key:StayList) { const text=drafts[key].trim();if(!text)return;changeTask(key,[...data.tasks[key],{id:crypto.randomUUID(),text,done:false}]);setDrafts(d=>({...d,[key]:''})); }
  return <><PageHeading eyebrow="Just for you" title="My stay." description="A small private corner for your own notes and everyday plans. Nothing on this page is sent to WardSpace." />
    <div className="rounded-[17px] bg-[#e4ebe1] border border-[#d2dfd0] p-5 mb-9 max-w-[850px]"><strong>Only on this device.</strong><p className="text-sm text-[#587064] mt-1">These notes are stored on this device only. They are not part of your medical record. Your tasks, notes, and check-in are not sent to the server or shared with staff. Anyone using this browser may be able to see them.</p></div>
    <div className="grid lg:grid-cols-2 gap-5">{lists.map(({key,title,placeholder})=><section key={key} className="surface p-6 md:p-8"><SectionTitle title={title}/><p className="text-[#708075] text-sm mb-4" data-testid={`progress-${key}`}>{data.tasks[key].filter(t=>t.done).length} of {data.tasks[key].length} done</p><div className="h-1.5 rounded-full bg-[#e1e8dd] mb-5 overflow-hidden"><div className="h-full bg-[#658a74] transition-[width]" style={{width:`${data.tasks[key].length?100*data.tasks[key].filter(t=>t.done).length/data.tasks[key].length:0}%`}}/></div><div className="space-y-2 mb-5">{data.tasks[key].map(t=><div key={t.id} className="flex items-center gap-3 rounded-xl bg-[#f0f1e9] p-3 min-h-[56px]"><label className="flex flex-1 items-center gap-3 cursor-pointer min-w-0"><input type="checkbox" className="w-5 h-5 shrink-0 accent-[#3b6554]" checked={t.done} onChange={()=>changeTask(key,data.tasks[key].map(x=>x.id===t.id?{...x,done:!x.done}:x))} data-testid={`checkbox-task-${t.id}`}/><span className={`break-words min-w-0 ${t.done?'line-through text-[#859086]':''}`}>{t.text}</span></label><button type="button" className="btn btn-danger !p-2 !min-w-[44px] shrink-0" aria-label={`Delete ${t.text}`} onClick={()=>changeTask(key,data.tasks[key].filter(x=>x.id!==t.id))} data-testid={`button-delete-task-${t.id}`}><Trash2 size={17}/></button></div>)}</div><form onSubmit={e=>{e.preventDefault();addTask(key)}} className="flex gap-2"><label htmlFor={`task-${key}`} className="sr-only">Add to {title}</label><input id={`task-${key}`} className="field min-w-0" value={drafts[key]} maxLength={180} placeholder={placeholder} onChange={e=>setDrafts(d=>({...d,[key]:e.target.value}))} data-testid={`input-task-${key}`}/><button className="btn btn-primary shrink-0" disabled={!drafts[key].trim()} data-testid={`button-add-task-${key}`}>Add</button></form></section>)}
    <section className="surface p-6 md:p-8"><SectionTitle title="A moment to check in" /><p className="text-[#708075] text-sm mb-5">Optional, and only for your own reference. This does not alert anyone.</p><div className="flex flex-wrap gap-2">{['Good','Okay','Difficult','Prefer not to say'].map(x=><button key={x} className={`btn !text-sm ${data.checkin===x?'btn-primary':'btn-outline'}`} onClick={()=>update({...data,checkin:data.checkin===x?'':x})} data-testid={`button-checkin-${x.toLowerCase().replaceAll(' ','-')}`} aria-pressed={data.checkin===x}>{x}</button>)}</div>{data.checkin==='Difficult'&&<p className="inset p-4 mt-5 text-sm text-[#52695c]">If you’d like to talk, please speak directly to a member of staff. This check-in is private to this browser and does not notify anyone.</p>}</section></div>
    <section className="surface p-6 md:p-8 mt-5"><label htmlFor="stay-notes" className="display text-2xl block mb-2">Notes to myself</label><p className="text-[#708075] text-sm mb-5">A thought, a reminder, or simply a place to write.</p><textarea id="stay-notes" className="field min-h-[180px]" value={data.notes} onChange={e=>update({...data,notes:e.target.value})} placeholder="Write whatever you’d like to remember…" data-testid="textarea-stay-notes"/><div className="flex flex-wrap items-center justify-between gap-3 mt-4"><span role="status" className="text-xs text-[#708075]" data-testid="status-local-save">{saved?'Saved in this browser':'Could not save in this browser'}</span><button className="btn btn-danger" onClick={()=>{if(window.confirm('Clear your tasks, check-in, and notes from this browser?')){try{localStorage.removeItem(storageKey)}catch{} setData(emptyStay())}}} data-testid="button-clear-stay">Clear my local information</button></div></section>
  </>;
}
export function AboutPage() { return <><PageHeading eyebrow="About & privacy" title="A place for the everyday." description="WardSpace is an experimental project exploring how simple technology could improve everyday life on inpatient wards by making information, activities and practical communication easier to access."/><div className="grid md:grid-cols-2 gap-5 max-w-[950px]"><div className="surface p-7"><BookOpen className="text-[#537768] mb-6"/><h2 className="display text-2xl">What you’ll find</h2><p className="mt-3 text-[#69786d]">Today’s schedule, activities, things to do, everyday answers, and a way to share non-urgent practical requests and ideas.</p></div><div className="surface p-7"><Heart className="text-[#b27c65] mb-6"/><h2 className="display text-2xl">Privacy in this prototype</h2><div className="mt-3 text-[#69786d] space-y-2"><p>This prototype does not form part of a medical record.</p><p>Do not enter confidential medical information.</p><p>Patient-facing features are designed to work without names or NHS numbers.</p><p>Personal My Stay notes remain on the device in the prototype. They are not sent to the server, but another person using this browser may see them.</p></div></div><div className="surface p-7 md:col-span-2"><h2 className="display text-2xl">A note about help</h2><p className="mt-3 text-[#69786d]">WardSpace is an information and activity companion. It does not provide medical advice, assess risk, or monitor messages for emergencies. For urgent help, speak directly to a member of staff in person.</p><div className="mt-6 flex gap-3 flex-wrap"><Link href="/guide" className="btn btn-primary" data-testid="link-about-guide">Explore the guide</Link><Link href="/" className="btn btn-outline" data-testid="link-about-home">Back to today</Link></div></div></div></>; }