import { useEffect, useState, type FormEvent } from 'react';
import { createPortal } from 'react-dom';
import { LogOut, Pencil, Plus, Trash2, X } from 'lucide-react';
import { getListStaffRequestsQueryKey, getListWardItemsQueryKey, useGetWardStaffStatus, useGetWardSummary, useListStaffRequests, useListWardItems, type WardItem, type WardItemInput } from '@workspace/api-client-react';
import { errorMessage, kindNames, kinds, useWardActions, type Kind } from '@/hooks/use-ward';
import { PageHeading, State } from '@/components/ward-ui';
import { StaffChallenge } from '@/components/staff-challenge';
import { DeviceSettings } from '@/components/device-settings';

const blank: WardItemInput = {title:'',description:'',category:'',date:'',recurrence:'none',recurrenceEndDate:'',time:'',endTime:'',location:'',capacity:undefined,duration:'',difficulty:'',content:'',preferredTime:'',status:'',response:'',published:true,active:true};
const labels: Partial<Record<keyof WardItemInput,string>> = {title:'Title',description:'Description',category:'Category',date:'Date',time:'Start time',endTime:'End time',location:'Location',capacity:'Capacity',duration:'Duration',difficulty:'Difficulty',content:'Long-form content or answer',preferredTime:'Preferred time',status:'Status',response:'Staff response'};
const fields: (keyof WardItemInput)[] = ['title','description','category','date','time','endTime','location','capacity','duration','difficulty','preferredTime','content','status','response'];
function ItemEditor({ kind, item, initial, onClose }: { kind: Kind; item: WardItem | null; initial?: Partial<WardItemInput>; onClose: () => void }) {
  const [form,setForm] = useState<WardItemInput>(item ? { ...blank, ...item } : {...blank,...initial});
  const [error,setError] = useState('');
  const actions = useWardActions();
  useEffect(()=>{setForm(item ? {...blank,...item} : {...blank,...initial});setError('')},[item,kind,initial]);
  async function submit(e: FormEvent) {
    e.preventDefault(); setError('');
    const payload: WardItemInput = {...form,title:form.title.trim()};
    if (!payload.title) {setError('Please add a title.');return}
    if (kind==='schedule') {
      payload.recurrence ||= 'none';
      if (payload.recurrence==='none') payload.recurrenceEndDate='';
      else if (!payload.date || !payload.recurrenceEndDate || payload.recurrenceEndDate<payload.date) {setError('Choose a repeat-until date on or after the first event date.');return}
    } else {delete payload.recurrence; delete payload.recurrenceEndDate}
    try { if (item) await actions.update.mutateAsync({kind,id:item.id,data:payload}); else await actions.create.mutateAsync({kind,data:payload}); onClose(); }
    catch(err) {setError(errorMessage(err))}
  }
    return createPortal(<div className="fixed inset-0 z-50 bg-[#24365c]/55 p-4 sm:p-6 overflow-y-auto overscroll-contain flex items-start justify-center" role="dialog" aria-modal="true" aria-label={item?'Edit content':'New content'} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
     <div className="surface min-w-0 w-full max-w-[760px] my-2 sm:my-4 p-4 min-[375px]:p-5 md:p-9 shadow-xl"><div className="flex justify-between gap-3 items-start mb-6"><div className="min-w-0"><p className="eyebrow [overflow-wrap:anywhere]">{kindNames[kind]}</p><h2 className="display text-3xl mt-2 [overflow-wrap:anywhere]">{item?'Edit entry':'New entry'}</h2></div><button type="button" className="btn btn-soft !p-2 !min-w-[44px] shrink-0" onClick={onClose} aria-label="Close editor" data-testid="button-close-editor"><X size={19}/></button></div>
       <form onSubmit={submit} className="grid min-w-0 grid-cols-1 md:grid-cols-2 gap-4">
          {fields.map(key => <div key={key} className={`min-w-0 ${['title','description','content','response'].includes(key)?'md:col-span-2':''}`}><label htmlFor={`editor-${key}`} className="label [overflow-wrap:anywhere]">{labels[key]}</label>{['description','content','response'].includes(key) ? <textarea id={`editor-${key}`} className="field !min-w-0 !max-w-full" maxLength={key==='description'?3000:undefined} value={String(form[key]??'')} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} data-testid={`input-editor-${key}`}/> : <input id={`editor-${key}`} className="field !min-w-0 !max-w-full" type={key==='date'?'date':key==='time'||key==='endTime'?'time':key==='capacity'?'number':'text'} min={key==='capacity'?0:undefined} required={key==='title'} maxLength={key==='title'?180:key==='category'?80:undefined} value={typeof form[key] === 'boolean' ? '' : form[key]??''} onChange={e=>setForm(v=>({...v,[key]:key==='capacity'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value}))} data-testid={`input-editor-${key}`} />}</div>)}
          {kind==='schedule'&&<div className="min-w-0 md:col-span-2 space-y-4">{item?.recurrence && item.recurrence!=='none' && <p className="text-sm text-[#415181]">Editing this entry updates the recurring schedule.</p>}<div className="min-w-0"><label className="label" htmlFor="schedule-repeat">Repeat</label><select id="schedule-repeat" className="field" value={form.recurrence||'none'} onChange={e=>setForm(v=>({...v,recurrence:e.target.value as WardItemInput['recurrence'],recurrenceEndDate:e.target.value==='none'?'':v.recurrenceEndDate}))}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekdays">Every weekday</option><option value="weekly">Weekly</option></select></div>{form.recurrence && form.recurrence!=='none' && <div className="min-w-0"><label className="label" htmlFor="schedule-repeat-until">Repeat until</label><input id="schedule-repeat-until" type="date" className="field" min={form.date||undefined} required value={form.recurrenceEndDate||''} onChange={e=>setForm(v=>({...v,recurrenceEndDate:e.target.value}))}/></div>}</div>}
         <div className="min-w-0 md:col-span-2 flex flex-wrap gap-5 py-2"><label className="flex min-w-0 max-w-full gap-2 items-start text-sm font-semibold [overflow-wrap:anywhere]"><input type="checkbox" checked={!!form.published} onChange={e=>setForm(v=>({...v,published:e.target.checked}))} className="w-5 h-5 shrink-0 accent-[#2B3D73]" data-testid="checkbox-published"/> {kind==='suggestions'?'Publish response publicly':'Published'}</label><label className="flex min-w-0 max-w-full gap-2 items-start text-sm font-semibold"><input type="checkbox" checked={!!form.active} onChange={e=>setForm(v=>({...v,active:e.target.checked}))} className="w-5 h-5 shrink-0 accent-[#2B3D73]" data-testid="checkbox-active"/> Active</label></div>
         {kind==='suggestions'&&<p className="min-w-0 md:col-span-2 text-xs text-[#586a7e] [overflow-wrap:anywhere]">Only publish a response after reviewing it for privacy. Public responses can appear in You Said / We Did.</p>}
         {error && <p className="min-w-0 md:col-span-2 text-[#a34f43] [overflow-wrap:anywhere]" role="alert" data-testid="error-editor">{error}</p>}
          <div className="min-w-0 md:col-span-2 flex flex-wrap max-[380px]:flex-col-reverse justify-end gap-2 pt-3 border-t border-[#d4e0e8]"><button type="button" className="btn btn-outline min-w-0 max-w-full max-[380px]:w-full text-center whitespace-normal [overflow-wrap:anywhere]" onClick={onClose} data-testid="button-cancel-editor">Cancel</button><button type="submit" className="btn btn-primary min-w-0 max-w-full max-[380px]:w-full text-center whitespace-normal [overflow-wrap:anywhere]" disabled={actions.create.isPending||actions.update.isPending} data-testid="button-save-editor">{actions.create.isPending||actions.update.isPending?'Saving…':item?'Save changes':'Create entry'}</button></div>
      </form>
    </div>
   </div>, document.body);
}

export function StaffPage() {
  const status = useGetWardStaffStatus();
  const summary = useGetWardSummary();
  const actions = useWardActions();
  const [pin,setPin] = useState('');
  const [loginError,setLoginError] = useState('');
  const [kind,setKind] = useState<Kind>('schedule');
  const [editing,setEditing] = useState<WardItem|null>(null);
  const [editorKind,setEditorKind] = useState<Kind>('schedule');
  const [initial,setInitial] = useState<Partial<WardItemInput>|undefined>();
  const [editorOpen,setEditorOpen] = useState(false);
  const [error,setError] = useState('');
  const [queueFilter,setQueueFilter] = useState('Open');
  const [quickActivity,setQuickActivity] = useState({title:'',time:'',location:'',description:''});
  const [quickAnnouncement,setQuickAnnouncement] = useState('');
  const [quickNotice,setQuickNotice] = useState('');
  const generalList = useListWardItems(kind,{query:{enabled:!!status.data?.authenticated&&kind!=='requests',queryKey:getListWardItemsQueryKey(kind)}});
  const requestList = useListStaffRequests(undefined,{query:{enabled:!!status.data?.authenticated&&kind==='requests',queryKey:getListStaffRequestsQueryKey()}});
  const list = kind==='requests'?requestList:generalList;
  const shown = (list.data||[]).filter(item=>kind!=='requests'||queueFilter==='All'||(queueFilter==='Open'?item.status?.toLowerCase()!=='completed':(item.status||'New').toLowerCase()===queueFilter.toLowerCase())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  function openEditor(editKind:Kind,item:WardItem|null=null,seed?:Partial<WardItemInput>){setEditorKind(editKind);setEditing(item);setInitial(seed);setEditorOpen(true)}
  async function setItem(item:WardItem,data:Partial<WardItemInput>){setError('');try{await actions.update.mutateAsync({kind,id:item.id,data})}catch(err){setError(errorMessage(err))}}
  if (status.isLoading) return <><PageHeading eyebrow="For staff" title="Staff area."/><State loading>{null}</State></>;
  if (status.isError) return <><PageHeading eyebrow="For staff" title="Staff area."/><State error retry={()=>status.refetch()}>{null}</State></>;
    if (!status.data?.authenticated) return <><PageHeading eyebrow="For staff" title="A place to keep things current." description="Staff can update activities, everyday information, requests, and the noticeboard here."/><div className="surface min-w-0 w-full max-w-[490px] p-5 min-[375px]:p-7 md:p-9"><p className="eyebrow mb-3">Staff sign in</p><h2 className="display text-3xl mb-3">Enter your PIN</h2><p className="text-sm text-[#586a7e] mb-6">Access is checked by the WardSpace server. Please use the staff credential provided by your administrator.</p><form onSubmit={async e=>{e.preventDefault();setLoginError('');try {await actions.login.mutateAsync({data:{pin}});setPin('')}catch(err){setLoginError(errorMessage(err))}}}><label className="label" htmlFor="staff-pin">Staff PIN</label><input id="staff-pin" type="password" inputMode="numeric" autoComplete="off" required className="field !min-w-0 !max-w-full mb-4" value={pin} onChange={e=>setPin(e.target.value)} data-testid="input-staff-pin"/>{loginError && <p role="alert" className="text-[#a34f43] text-sm mb-4 [overflow-wrap:anywhere]" data-testid="error-login">{loginError}</p>}<button className="btn btn-primary w-full min-w-0 text-center whitespace-normal [overflow-wrap:anywhere]" disabled={actions.login.isPending} data-testid="button-staff-login">{actions.login.isPending?'Checking…':'Enter staff area'}</button></form></div></>;
  async function deleteItem(item: WardItem) { if (!window.confirm(`Delete “${item.title}”? This cannot be undone.`))return;setError('');try {await actions.remove.mutateAsync({kind,id:item.id})}catch(err){setError(errorMessage(err))} }
  return <><PageHeading eyebrow="Staff workspace" title="Keep the everyday moving." description="Manage shared content and respond to non-urgent messages." action={<button className="btn btn-outline" disabled={actions.logout.isPending} onClick={async()=>{setError('');try{await actions.logout.mutateAsync()}catch(err){setError(errorMessage(err))}}} data-testid="button-staff-logout"><LogOut size={16}/> Sign out</button>}/>
     <div className="grid grid-cols-1 min-[390px]:grid-cols-2 min-[1350px]:grid-cols-5 gap-3 mb-7">{([
      ['Today’s activities',summary.data?.todayActivities],
      ['Coming up',summary.data?.upcomingActivities],
      ['Open requests',summary.data?.openRequests],
      ['New suggestions',summary.data?.newSuggestions],
      ['Announcements',summary.data?.announcements],
     ] as const).map(([label,value])=><div className="surface min-w-0 p-4 sm:p-5" key={label}><p className="eyebrow !tracking-[.09em] [overflow-wrap:anywhere]">{label}</p><strong className="display text-3xl block mt-2" data-testid={`value-staff-${label.toLowerCase().replaceAll(' ','-').replace('’','')}`}>{summary.isLoading?'—':value??'—'}</strong></div>)}</div>
    {summary.isError&&<p className="text-[#9d5547] mb-5">Couldn’t load the overview. <button className="underline" onClick={()=>summary.refetch()} data-testid="button-retry-staff-summary">Try again</button></p>}
      <DeviceSettings/>
      <StaffChallenge/>
      <section className="mb-9 min-w-0"><div className="flex justify-between items-end mb-5 gap-3"><div className="min-w-0"><p className="eyebrow">Quick update</p><h2 className="display text-3xl [overflow-wrap:anywhere]">Keep everyone in the loop.</h2></div></div>
        <div className="grid min-w-0 lg:grid-cols-2 gap-4"><form className="surface min-w-0 p-4 min-[375px]:p-5 md:p-6 space-y-3" onSubmit={async e=>{e.preventDefault();setQuickNotice('');try{const d=new Date();const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;await actions.create.mutateAsync({kind:'activities',data:{...quickActivity,date,status:'Published',published:true,active:true}});setQuickActivity({title:'',time:'',location:'',description:''});setQuickNotice('Activity published.')}catch(err){setQuickNotice(errorMessage(err))}}}><h3 className="display text-2xl [overflow-wrap:anywhere]">Add an activity</h3><div className="min-w-0"><label className="label" htmlFor="quick-title">Activity</label><input className="field !min-w-0 !max-w-full" id="quick-title" required maxLength={180} value={quickActivity.title} onChange={e=>setQuickActivity(v=>({...v,title:e.target.value}))}/></div><div className="grid min-w-0 grid-cols-1 min-[640px]:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 gap-3"><div className="min-w-0"><label className="label" htmlFor="quick-time">Time</label><input className="field !min-w-0 !max-w-full" id="quick-time" type="time" required value={quickActivity.time} onChange={e=>setQuickActivity(v=>({...v,time:e.target.value}))}/></div><div className="min-w-0"><label className="label" htmlFor="quick-location">Location</label><input className="field !min-w-0 !max-w-full" id="quick-location" required maxLength={100} value={quickActivity.location} onChange={e=>setQuickActivity(v=>({...v,location:e.target.value}))}/></div></div><div className="min-w-0"><label className="label" htmlFor="quick-description">Description (optional)</label><input className="field !min-w-0 !max-w-full" id="quick-description" maxLength={3000} value={quickActivity.description} onChange={e=>setQuickActivity(v=>({...v,description:e.target.value}))}/></div><button className="btn btn-primary max-w-full text-center whitespace-normal [overflow-wrap:anywhere]" disabled={actions.create.isPending}>Publish activity</button></form>
        <form className="surface min-w-0 p-4 min-[375px]:p-5 md:p-6 flex flex-col gap-3" onSubmit={async e=>{e.preventDefault();setQuickNotice('');try{await actions.create.mutateAsync({kind:'announcements',data:{title:quickAnnouncement.trim(),published:true,active:true}});setQuickAnnouncement('');setQuickNotice('Announcement posted.')}catch(err){setQuickNotice(errorMessage(err))}}}><h3 className="display text-2xl [overflow-wrap:anywhere]">Quick announcement</h3><label className="label" htmlFor="quick-announcement">What should the ward know?</label><textarea id="quick-announcement" className="field !min-w-0 !max-w-full flex-1" required maxLength={180} placeholder="Tonight’s film will start at 19:30." value={quickAnnouncement} onChange={e=>setQuickAnnouncement(e.target.value)}/><button className="btn btn-primary self-start max-w-full text-center whitespace-normal [overflow-wrap:anywhere]" disabled={actions.create.isPending}>Post announcement</button></form></div>{quickNotice&&<p className="inset p-4 mt-3 [overflow-wrap:anywhere]" role="status">{quickNotice}</p>}</section>
     {kind==='requests'&&<p className="inset p-4 mb-5 text-sm text-[#415181]">WardSpace practical requests should not replace normal ward communication or clinical escalation procedures. These are non-urgent messages, not an emergency channel.</p>}
     <div className="surface min-w-0 p-3 mb-7 flex flex-wrap gap-2">{kinds.map(k=><button key={k} className={`btn min-w-0 max-w-full text-center whitespace-normal [overflow-wrap:anywhere] !min-h-[44px] !text-[.82rem] ${kind===k?'btn-primary':'btn-soft'}`} onClick={()=>setKind(k)} data-testid={`button-staff-kind-${k}`}>{kindNames[k]}</button>)}</div>
     {kind==='requests'&&<div className="segmented mb-5" aria-label="Filter requests">{['Open','New','Acknowledged','Completed','All'].map(x=><button key={x} aria-pressed={queueFilter===x} onClick={()=>setQueueFilter(x)}>{x}</button>)}</div>}
     <div className="flex min-w-0 flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-5"><div className="min-w-0"><p className="eyebrow">Managing</p><h2 className="display text-[2rem] [overflow-wrap:anywhere]">{kindNames[kind]}</h2></div><button onClick={()=>openEditor(kind)} className="btn btn-primary w-full sm:w-auto max-w-full shrink-0 text-center whitespace-normal [overflow-wrap:anywhere]" data-testid="button-create-staff"><Plus size={17} className="shrink-0"/> Add new</button></div>
    {error && <div role="alert" className="bg-[#f5e5dd] text-[#9d5547] p-4 rounded-xl mb-4" data-testid="error-staff">{error}</div>}
      <State loading={list.isLoading} error={list.isError} empty={!shown.length} retry={()=>list.refetch()}><div className="space-y-3 min-w-0">{shown.map(item=><article key={item.id} className="surface min-w-0 p-4 min-[375px]:p-5 flex flex-col gap-4" data-testid={`staff-item-${item.id}`}><div className="flex min-w-0 flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex min-w-0 flex-wrap gap-2 mb-2"><span className="pill !max-w-full !whitespace-normal [overflow-wrap:anywhere]">{item.status||kindNames[kind]}</span>{item.category&&<span className="pill !max-w-full !whitespace-normal [overflow-wrap:anywhere]">{item.category}</span>}{kind==='schedule'&&item.recurrence && item.recurrence!=='none'&&<span className="pill">Repeats {item.recurrence==='weekdays'?'weekdays':item.recurrence}{item.recurrenceEndDate?` · Until ${new Date(`${item.recurrenceEndDate}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}`:''}</span>}{item.published===false && <span className="pill bg-[#f3e7da] !max-w-full !whitespace-normal [overflow-wrap:anywhere]">Unpublished</span>}{item.active===false && <span className="pill bg-[#f3e7da] !max-w-full !whitespace-normal [overflow-wrap:anywhere]">Inactive</span>}</div><h3 className="font-bold text-lg [overflow-wrap:anywhere]">{item.title}</h3><p className="text-sm text-[#586a7e] whitespace-pre-wrap [overflow-wrap:anywhere] mt-1">{item.description||item.content||'No additional detail'}</p>{item.description&&item.content&&<p className="text-sm text-[#586a7e] whitespace-pre-wrap [overflow-wrap:anywhere] mt-2">Content: {item.content}</p>}{item.location&&<p className="text-xs text-[#586a7e] mt-2 [overflow-wrap:anywhere]">Location: {item.location}</p>}{(kind==='activities'||kind==='activity-suggestions') && <p className="text-xs text-[#586a7e] mt-2">{item.interestCount} interested</p>}{(kind==='requests'||kind==='suggestions'||kind==='activity-suggestions')&&<p className="text-xs text-[#586a7e] mt-2">Submitted {new Date(item.createdAt).toLocaleString()}</p>}{item.response&&<p className="text-sm text-[#334669] whitespace-pre-wrap [overflow-wrap:anywhere] mt-2">Response: {item.response}</p>}</div><div className="flex min-w-0 flex-wrap gap-2 lg:shrink-0"><button className="btn btn-soft min-w-0 max-w-full text-center whitespace-normal [overflow-wrap:anywhere] !min-h-[44px]" onClick={()=>openEditor(kind,item)} data-testid={`button-edit-${item.id}`}><Pencil size={15} className="shrink-0"/> Edit</button><button className="btn btn-danger min-w-0 max-w-full text-center whitespace-normal [overflow-wrap:anywhere] !min-h-[44px]" disabled={actions.remove.isPending} onClick={()=>deleteItem(item)} data-testid={`button-delete-${item.id}`}><Trash2 size={15} className="shrink-0"/> Delete</button></div></div>
       <div className="flex min-w-0 flex-wrap gap-2 border-t border-[#d4e0e8] pt-3 [&>.btn]:min-w-0 [&>.btn]:max-w-full [&>.btn]:whitespace-normal [&>.btn]:text-center [&>.btn]:[overflow-wrap:anywhere] max-[374px]:[&>.btn]:w-full">
         {kind==='requests'&&(['New','Acknowledged','Completed'] as const).filter(s=>s.toLowerCase()!==item.status?.toLowerCase()).map(s=><button key={s} className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:s})} data-testid={`button-request-${s.toLowerCase()}-${item.id}`}>Mark {s}</button>)}
         {kind==='activities'&&<>{item.status?.toLowerCase()!=='published'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Published',published:true,active:true})} data-testid={`button-activity-publish-${item.id}`}>Publish</button>}{item.status?.toLowerCase()!=='cancelled'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Cancelled',active:false})} data-testid={`button-activity-cancel-${item.id}`}>Cancel</button>}{item.status?.toLowerCase()!=='completed'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Completed'})} data-testid={`button-activity-complete-${item.id}`}>Mark completed</button>}</>}
          {(kind==='suggestions'||kind==='activity-suggestions')&&<>{item.status?.toLowerCase()!=='approved'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Approved',active:true,published:true})} data-testid={`button-approve-${item.id}`}>Approve</button>}{item.status?.toLowerCase()!=='under review'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Under Review'})}>Under review</button>}{item.status?.toLowerCase()!=='archived'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Archived',active:false,published:false})}>Archive</button>}{item.status?.toLowerCase()!=='declined'&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{status:'Declined',active:false,published:false})} data-testid={`button-decline-${item.id}`}>Decline</button>}<button className="btn btn-soft !min-h-[44px] !text-xs" onClick={()=>openEditor('activities',null,{title:item.title,description:item.description||'',category:item.category||'',preferredTime:item.preferredTime||'',status:'Draft',published:false})} data-testid={`button-turn-into-activity-${item.id}`}>Turn into activity</button></>}
         {kind==='suggestions'&&<><button className="btn btn-soft !min-h-[44px] !text-xs" onClick={()=>openEditor(kind,item)} data-testid={`button-publish-response-${item.id}`}>Write / edit public response</button>{item.response&&<button className="btn btn-outline !min-h-[44px] !text-xs" disabled={actions.update.isPending} onClick={()=>setItem(item,{published:!item.published})} data-testid={`button-toggle-response-${item.id}`}>{item.published?'Unpublish response':'Publish response'}</button>}</>}
      </div></article>)}</div></State>
    {editorOpen && <ItemEditor kind={editorKind} item={editing} initial={initial} onClose={()=>setEditorOpen(false)}/>}
  </>;
}